# Generated by Django 5.1.6 on 2026-02-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrel',
            name='oil_type',
            field=models.CharField(choices=[('EVOO', 'Extra Virgin Olive Oil'), ('EVO', 'Virgin Olive Oil'), ('ROO', 'Refined Olive Oil'), ('OPO', 'Olive Pomace Oil')], max_length=128),
        ),
    ]
