# Generated by Django 5.1.6 on 2026-02-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_barrel_oil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.provider'),
        ),
    ]
